slugify <- function(value) {
  value |>
    tolower() |>
    gsub("[^a-z0-9]+", "-", x = _) |>
    gsub("(^-|-$)", "", x = _)
}

export_filename <- function(input, extension, prefix = "nordic-lung-trends") {
  paste(
    prefix,
    slugify(input$measure),
    slugify(input$sex),
    input$years[[1]],
    input$years[[2]],
    sep = "-"
  ) |>
    paste0(".", extension)
}

export_plot <- function(file, device, data, input) {
  plot <- make_trend_plot(
    data,
    measure = input$measure,
    sex = input$sex,
    statistic_label = rate_label(input$statistic),
    year_range = input$years
  )

  if (identical(device, "png")) {
    ggsave(
      file,
      plot = plot,
      device = "png",
      width = 13.333,
      height = 7.5,
      units = "in",
      dpi = 144,
      bg = "white"
    )
  } else if (identical(device, "pdf")) {
    ggsave(
      file,
      plot = plot,
      device = grDevices::pdf,
      width = 13.333,
      height = 7.5,
      units = "in",
      bg = "white"
    )
  } else {
    stop("Unsupported export device: ", device)
  }
}

build_methods_text <- function(input) {
  standard_population <- standard_population_for(input$statistic)
  source_reference <- paste(
    "Larønningen S, Arvidsson G, Bray F, et al. (2026).",
    "NORDCAN: Cancer Incidence, Mortality, Prevalence and Survival in the",
    "Nordic Countries, Version 9.6 (30.06.2026). Association of the Nordic",
    "Cancer Registries. Cancer Registry of Norway.",
    "https://nordcan.iarc.fr/, accessed 30 July 2026."
  )

  c(
    "NTOG Nordic Lung Cancer Trends — citation and methods",
    "======================================================",
    "",
    paste("Measure:", input$measure),
    paste("Sex:", input$sex),
    paste("Countries:", paste(input$countries, collapse = ", ")),
    paste("Years:", paste(input$years, collapse = "–")),
    paste("Cancer definition: Lung, ICD-10 C33–C34"),
    paste(
      if (identical(input$measure, "MIR")) {
        "Component rate definition:"
      } else {
        "Rate definition:"
      },
      rate_label(input$statistic)
    ),
    paste(
      "Standard population:",
      ifelse(is.na(standard_population), "Not applicable (crude rate)", standard_population)
    ),
    paste("Unit:", rate_unit(input$statistic, input$measure)),
    if (identical(input$measure, "MIR")) {
      "MIR formula: mortality rate / incidence rate."
    } else {
      character(0)
    },
    if (identical(input$measure, "MIR")) {
      paste(
        "Pairing: mortality and incidence rates matched by country, sex, year,",
        "cancer entity and rate definition."
      )
    } else {
      character(0)
    },
    "",
    "Recommended source reference",
    "----------------------------",
    source_reference,
    "",
    paste("Specific trend view:", NORDCAN_TREND_URL),
    "Snapshot retrieved: 30 July 2026",
    "",
    "Interpretation note",
    "-------------------",
    paste(
      "NORDCAN reports that Swedish lung-cancer incidence is not directly",
      "comparable with incidence in other Nordic countries and recommends",
      "mortality for cross-country comparisons."
    ),
    paste(
      "National coding, classification and registration practices can vary over",
      "time. These descriptive statistics do not by themselves establish causes."
    ),
    if (identical(input$measure, "MIR")) {
      paste(
        "MIR is a crude population indicator, not an individual risk measure and",
        "not case-fatality: deaths in a year need not be among cases diagnosed in",
        "that year. Age structure, screening, registry quality, lead-time bias and",
        "competing mortality can distort comparisons."
      )
    } else {
      character(0)
    },
    "",
    "Generated by NTOG Nordic Lung Cancer Trends.",
    "https://trends.ntog.org/"
  )
}
