slugify <- function(value) {
  value |>
    tolower() |>
    gsub("[^a-z0-9]+", "-", x = _) |>
    gsub("(^-|-$)", "", x = _)
}

export_filename <- function(input, extension, prefix = "nordic-lung-trends") {
  paste(
    prefix,
    slugify(input$measure),
    slugify(input$sex),
    input$years[[1]],
    input$years[[2]],
    sep = "-"
  ) |>
    paste0(".", extension)
}

export_plot <- function(file, device, data, input) {
  plot <- make_trend_plot(
    data,
    measure = input$measure,
    sex = input$sex,
    statistic_label = rate_label(input$statistic),
    year_range = input$years
  )

  if (identical(device, "png")) {
    ggsave(
      file,
      plot = plot,
      device = "png",
      width = 13.333,
      height = 7.5,
      units = "in",
      dpi = 144,
      bg = "white"
    )
  } else if (identical(device, "pdf")) {
    ggsave(
      file,
      plot = plot,
      device = grDevices::pdf,
      width = 13.333,
      height = 7.5,
      units = "in",
      bg = "white"
    )
  } else if (identical(device, "svg")) {
    if (!requireNamespace("svglite", quietly = TRUE)) {
      stop("SVG export requires the svglite package.")
    }
    ggsave(
      file,
      plot = plot,
      device = svglite::svglite,
      width = 13.333,
      height = 7.5,
      units = "in",
      bg = "white"
    )
  } else {
    stop("Unsupported export device: ", device)
  }
}

build_methods_text <- function(input, manifest = NULL) {
  standard_population <- standard_population_for(input$statistic)
  source_reference <- paste(
    "Larønningen S, Arvidsson G, Bray F, et al. (2026).",
    "NORDCAN: Cancer Incidence, Mortality, Prevalence and Survival in the",
    "Nordic Countries, Version 9.6 (30.06.2026). Association of the Nordic",
    "Cancer Registries. Cancer Registry of Norway.",
    "https://nordcan.iarc.fr/, accessed 30 July 2026."
  )

  release_lines <- if (is.null(manifest)) {
    character(0)
  } else {
    c(
      paste("App data release:", manifest$release_id),
      paste("Release schema:", manifest$schema_version),
      paste("SourceVahti schema:", manifest$sourcevahti_schema_version)
    )
  }

  c(
    "NTOG Nordic Lung Cancer Trends — citation and methods",
    "======================================================",
    "",
    paste("Measure:", input$measure),
    paste("Sex:", input$sex),
    paste("Countries:", paste(input$countries, collapse = ", ")),
    paste("Years:", paste(input$years, collapse = "–")),
    paste("Cancer definition: Lung, ICD-10 C33–C34"),
    paste(
      if (identical(input$measure, "MIR")) {
        "Component rate definition:"
      } else {
        "Rate definition:"
      },
      rate_label(input$statistic)
    ),
    paste(
      "Standard population:",
      ifelse(is.na(standard_population), "Not applicable (crude rate)", standard_population)
    ),
    paste("Unit:", rate_unit(input$statistic, input$measure)),
    if (identical(input$measure, "MIR")) {
      "MIR formula: mortality rate / incidence rate."
    } else {
      character(0)
    },
    if (identical(input$measure, "MIR")) {
      paste(
        "Pairing: mortality and incidence rates matched by country, sex, year,",
        "cancer entity and rate definition."
      )
    } else {
      character(0)
    },
    "",
    "Country graph identity",
    "----------------------",
    vapply(
      seq_len(nrow(COUNTRY_IDENTITIES)),
      function(index) {
        identity <- COUNTRY_IDENTITIES[index, , drop = FALSE]
        paste0(
          identity$country[[1]], ": ", identity$colour[[1]], ", ",
          identity$marker[[1]], ", ", identity$linetype[[1]]
        )
      },
      character(1)
    ),
    "",
    "Recommended source reference",
    "----------------------------",
    source_reference,
    "",
    paste("Specific trend view:", NORDCAN_TREND_URL),
    "Snapshot retrieved: 30 July 2026",
    release_lines,
    "",
    "Interpretation note",
    "-------------------",
    paste(
      "NORDCAN reports that Swedish lung-cancer incidence is not directly",
      "comparable with incidence in other Nordic countries and recommends",
      "mortality for cross-country comparisons."
    ),
    paste(
      "National coding, classification and registration practices can vary over",
      "time. These descriptive statistics do not by themselves establish causes."
    ),
    if (identical(input$measure, "MIR")) {
      paste(
        "MIR is a crude population indicator, not an individual risk measure and",
        "not case-fatality: deaths in a year need not be among cases diagnosed in",
        "that year. Age structure, screening, registry quality, lead-time bias and",
        "competing mortality can distort comparisons."
      )
    } else {
      character(0)
    },
    "",
    "Generated by NTOG Nordic Lung Cancer Trends.",
    "https://trends.ntog.org/"
  )
}

export_pptx <- function(file, data, input) {
  if (!requireNamespace("officer", quietly = TRUE) ||
      !requireNamespace("rvg", quietly = TRUE)) {
    stop("PowerPoint export requires the officer and rvg packages.")
  }
  plot <- make_trend_plot(
    data,
    measure = input$measure,
    sex = input$sex,
    statistic_label = rate_label(input$statistic),
    year_range = input$years
  )
  deck <- officer::read_pptx()
  layouts <- officer::layout_summary(deck)
  blank <- layouts[layouts$layout == "Blank", , drop = FALSE]
  chosen <- if (nrow(blank) > 0) {
    blank[1, , drop = FALSE]
  } else {
    layouts[1, , drop = FALSE]
  }
  deck <- officer::add_slide(
    deck,
    layout = chosen$layout,
    master = chosen$master
  )
  deck <- officer::ph_with(
    deck,
    value = rvg::dml(ggobj = plot),
    location = officer::ph_location_fullsize()
  )
  print(deck, target = file)
}

selection_metadata <- function(input, manifest) {
  list(
    title = "NTOG Nordic Lung Cancer Trends",
    generated_at = format(Sys.time(), tz = "UTC", usetz = TRUE),
    selection = list(
      measure = input$measure,
      sex = input$sex,
      countries = unname(input$countries),
      years = unname(input$years),
      statistic = input$statistic,
      rate_definition = rate_label(input$statistic),
      standard_population = standard_population_for(input$statistic)
    ),
    cancer = list(
      name = "Lung cancer",
      icd10 = "C33-C34"
    ),
    visual_encoding = list(
      country_identity = country_identity_metadata()
    ),
    release = manifest,
    application = "https://trends.ntog.org/",
    sourcevahti = "https://sourcevahti.vahtian.com/mcp"
  )
}

write_selection_metadata <- function(file, input, manifest) {
  jsonlite::write_json(
    selection_metadata(input, manifest),
    file,
    auto_unbox = TRUE,
    pretty = TRUE,
    null = "null"
  )
}

export_research_bundle <- function(file, data, input, manifest) {
  bundle_dir <- tempfile("ntog-lung-research-")
  dir.create(bundle_dir)
  on.exit(unlink(bundle_dir, recursive = TRUE), add = TRUE)

  png <- file.path(bundle_dir, "figure-16x9.png")
  pdf <- file.path(bundle_dir, "figure-vector.pdf")
  svg <- file.path(bundle_dir, "figure-vector.svg")
  csv <- file.path(bundle_dir, "selected-observations.csv")
  pptx <- file.path(bundle_dir, "editable-chart.pptx")
  methods <- file.path(bundle_dir, "methods-and-citation.txt")
  metadata <- file.path(bundle_dir, "selection-and-provenance.json")
  release <- file.path(bundle_dir, "data-release-manifest.json")

  export_plot(png, "png", data, input)
  export_plot(pdf, "pdf", data, input)
  export_plot(svg, "svg", data, input)
  export_pptx(pptx, data, input)
  readr::write_csv(data, csv, na = "")
  writeLines(build_methods_text(input, manifest), methods, useBytes = TRUE)
  write_selection_metadata(metadata, input, manifest)
  jsonlite::write_json(
    manifest,
    release,
    auto_unbox = TRUE,
    pretty = TRUE,
    null = "null"
  )

  zip::zipr(
    zipfile = file,
    files = list.files(bundle_dir, full.names = TRUE),
    root = bundle_dir
  )
}
